import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import QueryProvider from "@/utils/providers/QueryProvider";
import AuthProvider from "@/utils/providers/AuthProvider";
import { Toaster } from "@/components/ui/sonner";
import { JotaiProvider } from "@/components/Jotai-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Slack",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} relative `}>
        <AuthProvider>
          <JotaiProvider>
            <QueryProvider>
              {children}
              <Toaster className="bg-white text-black  " />
            </QueryProvider>
          </JotaiProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
